version: "3.3"

services:
  db:
    image: postgres:15-alpine
    container_name: "pg_db"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/repository/pgdata
    ports:
      - "5432:5432"
    restart: always

  app:
    build: .
    container_name: "golang_app"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: