version: "3.3"

services:
  db:
    image: postgres:15-alpine
    container_name: "pg_db"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/repository/pgdata
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data: